# Generated by Django 3.1.1 on 2020-09-13 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='tags',
        ),
    ]
