# Generated by Django 3.1.1 on 2020-09-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_auto_20200914_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='tags',
        ),
        migrations.AddField(
            model_name='home',
            name='tags',
            field=models.ManyToManyField(to='portfolio_app.Tags'),
        ),
    ]
