# Generated by Django 3.1.1 on 2020-09-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_auto_20200914_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='phone',
            field=models.CharField(default='8383966836', max_length=12),
        ),
    ]
