# Generated by Django 3.1.1 on 2020-09-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(upload_to='images/')),
                ('desc', models.TextField(max_length=200)),
                ('age', models.IntegerField(max_length=10)),
                ('residence', models.CharField(max_length=100)),
                ('freelance', models.CharField(choices=[('A', 'Available'), ('NA', 'Not Available')], default='A', max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(default='sunnydecent11@gmail.com', max_length=50)),
                ('phone', models.CharField(default='8383966836', max_length=12)),
                ('resume', models.FileField(upload_to='file/')),
            ],
        ),
    ]
