# Generated by Django 3.1.1 on 2020-09-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_resume_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_intro',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resume_intro',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resume_intro',
            name='desc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='resume_intro',
            name='residence',
            field=models.CharField(max_length=500),
        ),
    ]
