# Generated by Django 3.1.1 on 2020-09-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_auto_20200914_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_intro',
            name='freelance',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=30),
        ),
    ]
