# Generated by Django 3.1.1 on 2020-09-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0011_auto_20200914_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
