# Generated by Django 3.1.1 on 2020-09-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0012_resume_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('present', models.BooleanField()),
                ('designation', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('role_and_responsibility', models.CharField(max_length=200)),
            ],
        ),
    ]
