# Generated by Django 3.1.1 on 2020-09-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0013_resume_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_experience',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='resume_experience',
            name='to_date',
            field=models.DateField(),
        ),
    ]
