# Generated by Django 3.1.1 on 2020-09-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0018_auto_20200914_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_education',
            name='score',
            field=models.FloatField(),
        ),
    ]
