# Generated by Django 3.1.1 on 2020-09-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0019_auto_20200914_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_education',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
