# Generated by Django 3.1.1 on 2020-09-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0021_resume_language_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_language_skill',
            name='skill_rating',
            field=models.IntegerField(),
        ),
    ]
