# Generated by Django 3.1.1 on 2020-09-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0022_auto_20200914_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_coding_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('skill_rating', models.IntegerField()),
            ],
        ),
    ]
