# Generated by Django 3.1.1 on 2020-09-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0023_resume_coding_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
