# Generated by Django 3.1.1 on 2020-09-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0026_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_logos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logos', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
