# Generated by Django 3.1.1 on 2020-09-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0027_client_logos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
