# Generated by Django 3.1.1 on 2020-09-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0029_auto_20200914_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_text',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
